In [1]:
import numpy as np

In [ ]:
# just array formatting
def custom_complex_formatter(x):
    if np.isclose(x, 0):
        return "0"
    elif np.isreal(x):
        return f"{x.real:.1f}"
    elif np.isclose(x.real, 0):
        return f"{x.imag:.1f}j"
    else:
        return f"{x.real:.1f}+{x.imag:.1f}j"
    
np.set_printoptions(formatter={'all': custom_complex_formatter})

In [ ]:
def kronecker(a, b):
    return int(a==b)

def kronecker_combination(a, b, c, d):
    return kronecker(a, c) * kronecker(b, d) - kronecker(a, d) * kronecker(b, c)

# The generators (E^(index_pairs))_(pq)
index_pairs = [(0,1), (0,2), (0,3), (1,2), (3,1), (2,3)]

basis = np.zeros((6, 4, 4), dtype=np.complex_)

for k, index_pair in enumerate(index_pairs):
    basis_element = np.zeros((4,4))
    for i in range(4):
        for j in range(4):
            basis_element[i, j] = kronecker_combination(*index_pair, i, j)
    basis[k] = basis_element
    
display(basis)

array([[[0, 1.0, 0, 0],
        [-1.0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 1.0, 0],
        [0, 0, 0, 0],
        [-1.0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 1.0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [-1.0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 1.0, 0],
        [0, -1.0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, -1.0],
        [0, 0, 0, 0],
        [0, 1.0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 1.0],
        [0, 0, -1.0, 0]]])

In [96]:
def commutator(A, B):
    return A@B - B@A

# The New S and S_bar generators
S1 = -1j*(basis[0] + basis[-1])/2
S2 = -1j*(basis[1] + basis[-2])/2
S3 = -1j*(basis[2] + basis[-3])/2

S1_p = 1j*(basis[0] - basis[-1])/2
S2_p = 1j*(basis[1] - basis[-2])/2
S3_p = 1j*(basis[2] - basis[-3])/2

# I have confirmed all permutations.
display(commutator(S1, S2))
display(1j*S3) # there is no levi civita symb so beware of +-

print("------------------------")

display(commutator(S1_p, S2_p))
display(1j*S3_p) # there is no levi civita symb so beware of +-

array([[0, 0, 0, 0.5],
       [0, 0, 0.5, 0],
       [0, -0.5, 0, 0],
       [-0.5, 0, 0, 0]])

array([[0, 0, 0, 0.5],
       [0, 0, 0.5, 0],
       [0, -0.5, 0, 0],
       [-0.5, 0, 0, 0]])

------------------------


array([[0, 0, 0, -0.5],
       [0, 0, 0.5, 0],
       [0, -0.5, 0, 0],
       [0.5, 0, 0, 0]])

array([[0, 0, 0, -0.5],
       [0, 0, 0.5, 0],
       [0, -0.5, 0, 0],
       [0.5, 0, 0, 0]])